# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/Documents/prov_dev_client_ll_sample

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/Documents/prov_dev_client_ll_sample

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Documents/prov_dev_client_ll_sample/CMakeFiles /home/pi/Documents/prov_dev_client_ll_sample/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Documents/prov_dev_client_ll_sample/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named prov_dev_client

# Build rule for target.
prov_dev_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prov_dev_client
.PHONY : prov_dev_client

# fast build rule for target.
prov_dev_client/fast:
	$(MAKE) -f CMakeFiles/prov_dev_client.dir/build.make CMakeFiles/prov_dev_client.dir/build
.PHONY : prov_dev_client/fast

#=============================================================================
# Target rules for targets named umock_c

# Build rule for target.
umock_c: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 umock_c
.PHONY : umock_c

# fast build rule for target.
umock_c/fast:
	$(MAKE) -f out/deps/umock-c/CMakeFiles/umock_c.dir/build.make out/deps/umock-c/CMakeFiles/umock_c.dir/build
.PHONY : umock_c/fast

#=============================================================================
# Target rules for targets named parson

# Build rule for target.
parson: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 parson
.PHONY : parson

# fast build rule for target.
parson/fast:
	$(MAKE) -f out/deps/parson/CMakeFiles/parson.dir/build.make out/deps/parson/CMakeFiles/parson.dir/build
.PHONY : parson/fast

#=============================================================================
# Target rules for targets named aziotsharedutil

# Build rule for target.
aziotsharedutil: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 aziotsharedutil
.PHONY : aziotsharedutil

# fast build rule for target.
aziotsharedutil/fast:
	$(MAKE) -f out/c-utility/CMakeFiles/aziotsharedutil.dir/build.make out/c-utility/CMakeFiles/aziotsharedutil.dir/build
.PHONY : aziotsharedutil/fast

#=============================================================================
# Target rules for targets named uamqp

# Build rule for target.
uamqp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uamqp
.PHONY : uamqp

# fast build rule for target.
uamqp/fast:
	$(MAKE) -f out/uamqp/CMakeFiles/uamqp.dir/build.make out/uamqp/CMakeFiles/uamqp.dir/build
.PHONY : uamqp/fast

#=============================================================================
# Target rules for targets named umqtt

# Build rule for target.
umqtt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 umqtt
.PHONY : umqtt

# fast build rule for target.
umqtt/fast:
	$(MAKE) -f out/umqtt/CMakeFiles/umqtt.dir/build.make out/umqtt/CMakeFiles/umqtt.dir/build
.PHONY : umqtt/fast

#=============================================================================
# Target rules for targets named uhttp

# Build rule for target.
uhttp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uhttp
.PHONY : uhttp

# fast build rule for target.
uhttp/fast:
	$(MAKE) -f out/deps/uhttp/CMakeFiles/uhttp.dir/build.make out/deps/uhttp/CMakeFiles/uhttp.dir/build
.PHONY : uhttp/fast

#=============================================================================
# Target rules for targets named iothub_service_client

# Build rule for target.
iothub_service_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iothub_service_client
.PHONY : iothub_service_client

# fast build rule for target.
iothub_service_client/fast:
	$(MAKE) -f out/iothub_service_client/CMakeFiles/iothub_service_client.dir/build.make out/iothub_service_client/CMakeFiles/iothub_service_client.dir/build
.PHONY : iothub_service_client/fast

#=============================================================================
# Target rules for targets named provisioning_service_client

# Build rule for target.
provisioning_service_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 provisioning_service_client
.PHONY : provisioning_service_client

# fast build rule for target.
provisioning_service_client/fast:
	$(MAKE) -f out/provisioning_service_client/CMakeFiles/provisioning_service_client.dir/build.make out/provisioning_service_client/CMakeFiles/provisioning_service_client.dir/build
.PHONY : provisioning_service_client/fast

#=============================================================================
# Target rules for targets named prov_device_client

# Build rule for target.
prov_device_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prov_device_client
.PHONY : prov_device_client

# fast build rule for target.
prov_device_client/fast:
	$(MAKE) -f out/provisioning_client/CMakeFiles/prov_device_client.dir/build.make out/provisioning_client/CMakeFiles/prov_device_client.dir/build
.PHONY : prov_device_client/fast

#=============================================================================
# Target rules for targets named prov_device_ll_client

# Build rule for target.
prov_device_ll_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prov_device_ll_client
.PHONY : prov_device_ll_client

# fast build rule for target.
prov_device_ll_client/fast:
	$(MAKE) -f out/provisioning_client/CMakeFiles/prov_device_ll_client.dir/build.make out/provisioning_client/CMakeFiles/prov_device_ll_client.dir/build
.PHONY : prov_device_ll_client/fast

#=============================================================================
# Target rules for targets named prov_mqtt_transport

# Build rule for target.
prov_mqtt_transport: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prov_mqtt_transport
.PHONY : prov_mqtt_transport

# fast build rule for target.
prov_mqtt_transport/fast:
	$(MAKE) -f out/provisioning_client/CMakeFiles/prov_mqtt_transport.dir/build.make out/provisioning_client/CMakeFiles/prov_mqtt_transport.dir/build
.PHONY : prov_mqtt_transport/fast

#=============================================================================
# Target rules for targets named hsm_security_client

# Build rule for target.
hsm_security_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hsm_security_client
.PHONY : hsm_security_client

# fast build rule for target.
hsm_security_client/fast:
	$(MAKE) -f out/provisioning_client/CMakeFiles/hsm_security_client.dir/build.make out/provisioning_client/CMakeFiles/hsm_security_client.dir/build
.PHONY : hsm_security_client/fast

#=============================================================================
# Target rules for targets named prov_http_transport

# Build rule for target.
prov_http_transport: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prov_http_transport
.PHONY : prov_http_transport

# fast build rule for target.
prov_http_transport/fast:
	$(MAKE) -f out/provisioning_client/CMakeFiles/prov_http_transport.dir/build.make out/provisioning_client/CMakeFiles/prov_http_transport.dir/build
.PHONY : prov_http_transport/fast

#=============================================================================
# Target rules for targets named prov_amqp_ws_transport

# Build rule for target.
prov_amqp_ws_transport: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prov_amqp_ws_transport
.PHONY : prov_amqp_ws_transport

# fast build rule for target.
prov_amqp_ws_transport/fast:
	$(MAKE) -f out/provisioning_client/CMakeFiles/prov_amqp_ws_transport.dir/build.make out/provisioning_client/CMakeFiles/prov_amqp_ws_transport.dir/build
.PHONY : prov_amqp_ws_transport/fast

#=============================================================================
# Target rules for targets named prov_amqp_transport

# Build rule for target.
prov_amqp_transport: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prov_amqp_transport
.PHONY : prov_amqp_transport

# fast build rule for target.
prov_amqp_transport/fast:
	$(MAKE) -f out/provisioning_client/CMakeFiles/prov_amqp_transport.dir/build.make out/provisioning_client/CMakeFiles/prov_amqp_transport.dir/build
.PHONY : prov_amqp_transport/fast

#=============================================================================
# Target rules for targets named prov_mqtt_ws_transport

# Build rule for target.
prov_mqtt_ws_transport: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prov_mqtt_ws_transport
.PHONY : prov_mqtt_ws_transport

# fast build rule for target.
prov_mqtt_ws_transport/fast:
	$(MAKE) -f out/provisioning_client/CMakeFiles/prov_mqtt_ws_transport.dir/build.make out/provisioning_client/CMakeFiles/prov_mqtt_ws_transport.dir/build
.PHONY : prov_mqtt_ws_transport/fast

#=============================================================================
# Target rules for targets named prov_auth_client

# Build rule for target.
prov_auth_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prov_auth_client
.PHONY : prov_auth_client

# fast build rule for target.
prov_auth_client/fast:
	$(MAKE) -f out/provisioning_client/CMakeFiles/prov_auth_client.dir/build.make out/provisioning_client/CMakeFiles/prov_auth_client.dir/build
.PHONY : prov_auth_client/fast

#=============================================================================
# Target rules for targets named iothub_client_mqtt_transport

# Build rule for target.
iothub_client_mqtt_transport: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iothub_client_mqtt_transport
.PHONY : iothub_client_mqtt_transport

# fast build rule for target.
iothub_client_mqtt_transport/fast:
	$(MAKE) -f out/iothub_client/CMakeFiles/iothub_client_mqtt_transport.dir/build.make out/iothub_client/CMakeFiles/iothub_client_mqtt_transport.dir/build
.PHONY : iothub_client_mqtt_transport/fast

#=============================================================================
# Target rules for targets named iothub_client_amqp_ws_transport

# Build rule for target.
iothub_client_amqp_ws_transport: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iothub_client_amqp_ws_transport
.PHONY : iothub_client_amqp_ws_transport

# fast build rule for target.
iothub_client_amqp_ws_transport/fast:
	$(MAKE) -f out/iothub_client/CMakeFiles/iothub_client_amqp_ws_transport.dir/build.make out/iothub_client/CMakeFiles/iothub_client_amqp_ws_transport.dir/build
.PHONY : iothub_client_amqp_ws_transport/fast

#=============================================================================
# Target rules for targets named iothub_client_amqp_transport

# Build rule for target.
iothub_client_amqp_transport: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iothub_client_amqp_transport
.PHONY : iothub_client_amqp_transport

# fast build rule for target.
iothub_client_amqp_transport/fast:
	$(MAKE) -f out/iothub_client/CMakeFiles/iothub_client_amqp_transport.dir/build.make out/iothub_client/CMakeFiles/iothub_client_amqp_transport.dir/build
.PHONY : iothub_client_amqp_transport/fast

#=============================================================================
# Target rules for targets named iothub_client_http_transport

# Build rule for target.
iothub_client_http_transport: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iothub_client_http_transport
.PHONY : iothub_client_http_transport

# fast build rule for target.
iothub_client_http_transport/fast:
	$(MAKE) -f out/iothub_client/CMakeFiles/iothub_client_http_transport.dir/build.make out/iothub_client/CMakeFiles/iothub_client_http_transport.dir/build
.PHONY : iothub_client_http_transport/fast

#=============================================================================
# Target rules for targets named iothub_client_mqtt_ws_transport

# Build rule for target.
iothub_client_mqtt_ws_transport: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iothub_client_mqtt_ws_transport
.PHONY : iothub_client_mqtt_ws_transport

# fast build rule for target.
iothub_client_mqtt_ws_transport/fast:
	$(MAKE) -f out/iothub_client/CMakeFiles/iothub_client_mqtt_ws_transport.dir/build.make out/iothub_client/CMakeFiles/iothub_client_mqtt_ws_transport.dir/build
.PHONY : iothub_client_mqtt_ws_transport/fast

#=============================================================================
# Target rules for targets named iothub_client

# Build rule for target.
iothub_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iothub_client
.PHONY : iothub_client

# fast build rule for target.
iothub_client/fast:
	$(MAKE) -f out/iothub_client/CMakeFiles/iothub_client.dir/build.make out/iothub_client/CMakeFiles/iothub_client.dir/build
.PHONY : iothub_client/fast

#=============================================================================
# Target rules for targets named serializer

# Build rule for target.
serializer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 serializer
.PHONY : serializer

# fast build rule for target.
serializer/fast:
	$(MAKE) -f out/serializer/CMakeFiles/serializer.dir/build.make out/serializer/CMakeFiles/serializer.dir/build
.PHONY : serializer/fast

application.o: application.c.o

.PHONY : application.o

# target to build an object file
application.c.o:
	$(MAKE) -f CMakeFiles/prov_dev_client.dir/build.make CMakeFiles/prov_dev_client.dir/application.c.o
.PHONY : application.c.o

application.i: application.c.i

.PHONY : application.i

# target to preprocess a source file
application.c.i:
	$(MAKE) -f CMakeFiles/prov_dev_client.dir/build.make CMakeFiles/prov_dev_client.dir/application.c.i
.PHONY : application.c.i

application.s: application.c.s

.PHONY : application.s

# target to generate assembly for a file
application.c.s:
	$(MAKE) -f CMakeFiles/prov_dev_client.dir/build.make CMakeFiles/prov_dev_client.dir/application.c.s
.PHONY : application.c.s

prov_dev_client.o: prov_dev_client.c.o

.PHONY : prov_dev_client.o

# target to build an object file
prov_dev_client.c.o:
	$(MAKE) -f CMakeFiles/prov_dev_client.dir/build.make CMakeFiles/prov_dev_client.dir/prov_dev_client.c.o
.PHONY : prov_dev_client.c.o

prov_dev_client.i: prov_dev_client.c.i

.PHONY : prov_dev_client.i

# target to preprocess a source file
prov_dev_client.c.i:
	$(MAKE) -f CMakeFiles/prov_dev_client.dir/build.make CMakeFiles/prov_dev_client.dir/prov_dev_client.c.i
.PHONY : prov_dev_client.c.i

prov_dev_client.s: prov_dev_client.c.s

.PHONY : prov_dev_client.s

# target to generate assembly for a file
prov_dev_client.c.s:
	$(MAKE) -f CMakeFiles/prov_dev_client.dir/build.make CMakeFiles/prov_dev_client.dir/prov_dev_client.c.s
.PHONY : prov_dev_client.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... install"
	@echo "... prov_dev_client"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... umock_c"
	@echo "... parson"
	@echo "... aziotsharedutil"
	@echo "... uamqp"
	@echo "... umqtt"
	@echo "... uhttp"
	@echo "... iothub_service_client"
	@echo "... provisioning_service_client"
	@echo "... prov_device_client"
	@echo "... prov_device_ll_client"
	@echo "... prov_mqtt_transport"
	@echo "... hsm_security_client"
	@echo "... prov_http_transport"
	@echo "... prov_amqp_ws_transport"
	@echo "... prov_amqp_transport"
	@echo "... prov_mqtt_ws_transport"
	@echo "... prov_auth_client"
	@echo "... iothub_client_mqtt_transport"
	@echo "... iothub_client_amqp_ws_transport"
	@echo "... iothub_client_amqp_transport"
	@echo "... iothub_client_http_transport"
	@echo "... iothub_client_mqtt_ws_transport"
	@echo "... iothub_client"
	@echo "... serializer"
	@echo "... application.o"
	@echo "... application.i"
	@echo "... application.s"
	@echo "... prov_dev_client.o"
	@echo "... prov_dev_client.i"
	@echo "... prov_dev_client.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

